/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.view;

import qlbg.bean.DanhMucBean;
import Controller.ChuyenManHinhController;
import java.util.ArrayList;
import java.util.List;
/**
 *
 * @author anhsa
 */
public class MainFrame extends javax.swing.JFrame {
    public String loginUsername ="";

    /**
     * Creates new form MainFrame
     */
    public MainFrame(String username) {
        initComponents();
        setTitle("Quản lý bán giày");
        ChuyenManHinhController controller=new ChuyenManHinhController(jpnView);
        controller.setView(jbnNH, jlbNH);
        List<DanhMucBean> listItem=new ArrayList<>();
        listItem.add(new DanhMucBean("NhapHang",jbnNH,jlbNH));
        listItem.add(new DanhMucBean("BanHang",jbnBH,jlbBH));
        listItem.add(new DanhMucBean("TaiKhoan",jpnTkhoan,jlbTKhoan));
        listItem.add(new DanhMucBean("SanPham",jpnSP,jlbSP));
        listItem.add(new DanhMucBean("NhaCungCap",jpnNCC,jlbNCC));
        listItem.add(new DanhMucBean("HoaDon",jpnHD,jlbHD));
        listItem.add(new DanhMucBean("KhachHang",jpnKH,jlbKH));
        listItem.add(new DanhMucBean("ThongKe",jpnTK,jlbTK));
        listItem.add(new DanhMucBean("KhuyenMai",jpnKM,jlbKM));
        txtUsername.setText(username);
        loginUsername = username;
        controller.setEvent(listItem);
        
    }
    public MainFrame() {  
    }
    public String getUsername(){
        return loginUsername;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnMain = new javax.swing.JPanel();
        jpnMenu = new javax.swing.JPanel();
        jbnNH = new javax.swing.JPanel();
        jlbNH = new javax.swing.JLabel();
        jpnTkhoan = new javax.swing.JPanel();
        jlbTKhoan = new javax.swing.JLabel();
        jpnSP = new javax.swing.JPanel();
        jlbSP = new javax.swing.JLabel();
        jpnNCC = new javax.swing.JPanel();
        jlbNCC = new javax.swing.JLabel();
        jpnHD = new javax.swing.JPanel();
        jlbHD = new javax.swing.JLabel();
        jpnKH = new javax.swing.JPanel();
        jlbKH = new javax.swing.JLabel();
        jpnTK = new javax.swing.JPanel();
        jlbTK = new javax.swing.JLabel();
        jpnKM = new javax.swing.JPanel();
        jlbKM = new javax.swing.JLabel();
        jpnDX = new javax.swing.JPanel();
        jlbDX = new javax.swing.JLabel();
        jbnBH = new javax.swing.JPanel();
        jlbBH = new javax.swing.JLabel();
        txtUsername = new javax.swing.JLabel();
        jpnView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setResizable(false);

        jpnMain.setPreferredSize(new java.awt.Dimension(1400, 800));

        jpnMenu.setBackground(new java.awt.Color(0, 102, 102));
        jpnMenu.setPreferredSize(new java.awt.Dimension(200, 800));

        jbnNH.setBackground(new java.awt.Color(0, 102, 102));

        jlbNH.setBackground(new java.awt.Color(0, 0, 0));
        jlbNH.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jlbNH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ing/home1.png"))); // NOI18N
        jlbNH.setText("Nhap Hang");

        javax.swing.GroupLayout jbnNHLayout = new javax.swing.GroupLayout(jbnNH);
        jbnNH.setLayout(jbnNHLayout);
        jbnNHLayout.setHorizontalGroup(
            jbnNHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbNH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jbnNHLayout.setVerticalGroup(
            jbnNHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbNH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        jpnTkhoan.setBackground(new java.awt.Color(0, 102, 102));

        jlbTKhoan.setBackground(new java.awt.Color(255, 255, 255));
        jlbTKhoan.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jlbTKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ing/user.png"))); // NOI18N
        jlbTKhoan.setText("Tài khoản");

        javax.swing.GroupLayout jpnTkhoanLayout = new javax.swing.GroupLayout(jpnTkhoan);
        jpnTkhoan.setLayout(jpnTkhoanLayout);
        jpnTkhoanLayout.setHorizontalGroup(
            jpnTkhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbTKhoan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnTkhoanLayout.setVerticalGroup(
            jpnTkhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbTKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jpnSP.setBackground(new java.awt.Color(0, 102, 102));

        jlbSP.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jlbSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ing/product.png"))); // NOI18N
        jlbSP.setText("Sản phẩm");

        javax.swing.GroupLayout jpnSPLayout = new javax.swing.GroupLayout(jpnSP);
        jpnSP.setLayout(jpnSPLayout);
        jpnSPLayout.setHorizontalGroup(
            jpnSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnSPLayout.setVerticalGroup(
            jpnSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jpnNCC.setBackground(new java.awt.Color(0, 102, 102));

        jlbNCC.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jlbNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ing/production.png"))); // NOI18N
        jlbNCC.setText("Nhà cung cấp");

        javax.swing.GroupLayout jpnNCCLayout = new javax.swing.GroupLayout(jpnNCC);
        jpnNCC.setLayout(jpnNCCLayout);
        jpnNCCLayout.setHorizontalGroup(
            jpnNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnNCCLayout.setVerticalGroup(
            jpnNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbNCC, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jpnHD.setBackground(new java.awt.Color(0, 102, 102));

        jlbHD.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jlbHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ing/bill.png"))); // NOI18N
        jlbHD.setText("Hóa đơn");

        javax.swing.GroupLayout jpnHDLayout = new javax.swing.GroupLayout(jpnHD);
        jpnHD.setLayout(jpnHDLayout);
        jpnHDLayout.setHorizontalGroup(
            jpnHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnHDLayout.setVerticalGroup(
            jpnHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbHD, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jpnKH.setBackground(new java.awt.Color(0, 102, 102));

        jlbKH.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jlbKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ing/customer.png"))); // NOI18N
        jlbKH.setText("Khách hàng");

        javax.swing.GroupLayout jpnKHLayout = new javax.swing.GroupLayout(jpnKH);
        jpnKH.setLayout(jpnKHLayout);
        jpnKHLayout.setHorizontalGroup(
            jpnKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbKH, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jpnKHLayout.setVerticalGroup(
            jpnKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbKH, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jpnTK.setBackground(new java.awt.Color(0, 102, 102));

        jlbTK.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jlbTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ing/trend.png"))); // NOI18N
        jlbTK.setText("Thống kê");

        javax.swing.GroupLayout jpnTKLayout = new javax.swing.GroupLayout(jpnTK);
        jpnTK.setLayout(jpnTKLayout);
        jpnTKLayout.setHorizontalGroup(
            jpnTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnTKLayout.setVerticalGroup(
            jpnTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbTK, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jpnKM.setBackground(new java.awt.Color(0, 102, 102));

        jlbKM.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jlbKM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ing/promo-code.png"))); // NOI18N
        jlbKM.setText("Voucher");

        javax.swing.GroupLayout jpnKMLayout = new javax.swing.GroupLayout(jpnKM);
        jpnKM.setLayout(jpnKMLayout);
        jpnKMLayout.setHorizontalGroup(
            jpnKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbKM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnKMLayout.setVerticalGroup(
            jpnKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbKM, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jpnDX.setBackground(new java.awt.Color(0, 102, 102));

        jlbDX.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jlbDX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ing/logout.png"))); // NOI18N
        jlbDX.setText("Đăng xuất");

        javax.swing.GroupLayout jpnDXLayout = new javax.swing.GroupLayout(jpnDX);
        jpnDX.setLayout(jpnDXLayout);
        jpnDXLayout.setHorizontalGroup(
            jpnDXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbDX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnDXLayout.setVerticalGroup(
            jpnDXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbDX, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jbnBH.setBackground(new java.awt.Color(0, 102, 102));

        jlbBH.setBackground(new java.awt.Color(0, 0, 0));
        jlbBH.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jlbBH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ing/home1.png"))); // NOI18N
        jlbBH.setText("Bán Hàng");

        javax.swing.GroupLayout jbnBHLayout = new javax.swing.GroupLayout(jbnBH);
        jbnBH.setLayout(jbnBHLayout);
        jbnBHLayout.setHorizontalGroup(
            jbnBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbBH, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jbnBHLayout.setVerticalGroup(
            jbnBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jbnBHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbBH, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
        );

        txtUsername.setText("Username");

        javax.swing.GroupLayout jpnMenuLayout = new javax.swing.GroupLayout(jpnMenu);
        jpnMenu.setLayout(jpnMenuLayout);
        jpnMenuLayout.setHorizontalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbnNH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnTkhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnKM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnDX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jbnBH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnMenuLayout.setVerticalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jbnNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnTkhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnDX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpnMenuLayout.createSequentialGroup()
                    .addGap(69, 69, 69)
                    .addComponent(jbnBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(682, Short.MAX_VALUE)))
        );

        jpnView.setPreferredSize(new java.awt.Dimension(1200, 1000));

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1194, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnMainLayout = new javax.swing.GroupLayout(jpnMain);
        jpnMain.setLayout(jpnMainLayout);
        jpnMainLayout.setHorizontalGroup(
            jpnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMainLayout.createSequentialGroup()
                .addComponent(jpnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, 1194, Short.MAX_VALUE))
        );
        jpnMainLayout.setVerticalGroup(
            jpnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
            .addComponent(jpnMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
        );

        jpnMenu.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnMain, javax.swing.GroupLayout.PREFERRED_SIZE, 640, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jbnBH;
    private javax.swing.JPanel jbnNH;
    private javax.swing.JLabel jlbBH;
    private javax.swing.JLabel jlbBH2;
    private javax.swing.JLabel jlbDX;
    private javax.swing.JLabel jlbHD;
    private javax.swing.JLabel jlbKH;
    private javax.swing.JLabel jlbKM;
    private javax.swing.JLabel jlbNCC;
    private javax.swing.JLabel jlbNH;
    private javax.swing.JLabel jlbSP;
    private javax.swing.JLabel jlbTK;
    private javax.swing.JLabel jlbTKhoan;
    private javax.swing.JPanel jpnBH1;
    private javax.swing.JPanel jpnDX;
    private javax.swing.JPanel jpnHD;
    private javax.swing.JPanel jpnKH;
    private javax.swing.JPanel jpnKM;
    private javax.swing.JPanel jpnMain;
    private javax.swing.JPanel jpnMenu;
    private javax.swing.JPanel jpnNCC;
    private javax.swing.JPanel jpnSP;
    private javax.swing.JPanel jpnTK;
    private javax.swing.JPanel jpnTkhoan;
    private javax.swing.JPanel jpnView;
    private javax.swing.JLabel txtUsername;
    // End of variables declaration//GEN-END:variables

    
}
