/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.view;

import BLL.staffBLL;
import DTO.staff;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anhsa
 */
public class TaiKhoanGUI extends javax.swing.JPanel {
    private ArrayList<staff> listStaff;
    DefaultTableModel model;
    /**
     * Creates new form TaiKhoanGUI
     */
    public TaiKhoanGUI() {
        initComponents();
        load();
    }
    public void load(){
        listStaff = staffBLL.readStaff();
        model = (DefaultTableModel) jTable12.getModel();
        showTable();
    }
    public void showTable(){
        model.setRowCount(0);
        for(staff s : listStaff){
            model.addRow(new Object[]{
                s.getStaffId(), s.getPassword(), s.getStaffName(), s.getPower(), s.getPhone(), s.getAddress()
            });
        }
    }
    public void showTableSearch(ArrayList<staff> listStaffSearch){
        model = (DefaultTableModel) jTable12.getModel();
        model.setRowCount(0);
        for(staff s : listStaffSearch){
            model.addRow(new Object[]{
                s.getStaffId(), s.getPassword(), s.getStaffName(), s.getPower(), s.getPhone(), s.getAddress()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel88 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jButton38 = new javax.swing.JButton();
        btnAadd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();
        jLabel91 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable12 = new javax.swing.JTable();
        CBpower = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1200, 800));

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));
        jPanel10.setPreferredSize(new java.awt.Dimension(1200, 800));

        jLabel71.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel71.setText("Quản lý tài khoản");

        jLabel72.setText("Tài khoản");

        jLabel73.setText("Mật khẩu");

        jLabel74.setText("Quyền");

        jLabel75.setText("Họ tên");

        jLabel76.setText("Số điện thoại");

        jLabel88.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel88.setText("Tìm kiếm");

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        jButton38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ing/search-interface-symbol1.png"))); // NOI18N
        jButton38.setText("Tìm");
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });

        btnAadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ing/plus.png"))); // NOI18N
        btnAadd.setText("Thêm");
        btnAadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAaddActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ing/setting.png"))); // NOI18N
        btnUpdate.setText("Sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ing/delete.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnrefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ing/reload.png"))); // NOI18N
        btnrefresh.setText("Tạo mới");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });

        jLabel91.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel91.setText("Danh sách tài khoản");

        jTable12.setAutoCreateRowSorter(true);
        jTable12.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tài khoản", "Mật khẩu", "Họ và tên", "Quyền", "Số điện thoại", "Địa chỉ"
            }
        ));
        jTable12.setCellSelectionEnabled(true);
        jTable12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable12MouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(jTable12);
        jTable12.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        CBpower.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân viên", "Admin", "Owner" }));
        CBpower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBpowerActionPerformed(evt);
            }
        });

        jLabel1.setText("Địa chỉ");

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel88, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel76, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(jLabel72, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel73, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel74, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel75, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPassword)
                            .addComponent(txtUsername)
                            .addComponent(CBpower, 0, 104, Short.MAX_VALUE)
                            .addComponent(txtName)
                            .addComponent(txtPhone)
                            .addComponent(txtAddress))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAadd, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnrefresh)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel91, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel71)
                    .addComponent(jLabel91))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel72)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAadd))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel73)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdate))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel74)
                            .addComponent(btnDelete)
                            .addComponent(CBpower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel75)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnrefresh))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel76)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel88)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton38))
                        .addContainerGap())
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1014, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 1014, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed
    public void clear(){
        txtAddress.setText("");
        txtName.setText("");
        txtPassword.setText("");
        txtPhone.setText("");
        txtUsername.setText("");
        CBpower.setSelectedItem("Nhân viên");
    }
    private void jTable12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable12MouseClicked
        // TODO add your handling code here:
        int row = jTable12.getSelectedRow();
        if(row >=0){
            txtUsername.setText(jTable12.getValueAt(row, 0).toString());
            txtPassword.setText(jTable12.getValueAt(row, 1).toString());
            txtName.setText(jTable12.getValueAt(row, 2).toString());
            String power =jTable12.getValueAt(row, 3).toString();
            if(power.equals("1")) CBpower.setSelectedItem("Nhân viên");
            else if(power.equals("2"))CBpower.setSelectedItem("Admin");
            else CBpower.setSelectedItem("Owner");
            txtPhone.setText(jTable12.getValueAt(row, 4).toString());
            txtAddress.setText(jTable12.getValueAt(row, 5).toString());
        }
        
    }//GEN-LAST:event_jTable12MouseClicked

    private void CBpowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBpowerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBpowerActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void btnAaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAaddActionPerformed

        String staffName = txtName.getText();
        String staffphone = txtPhone.getText();
        String staffId = txtUsername.getText();
        String staffPassword = txtPassword.getText();
        String staffPower = CBpower.getSelectedItem().toString();
        int power;
        if(staffPower.equals("Nhân viên")) power =1;
        else if(staffPower.equals("Admin")) power =2;
        else power = 3;
        String staffAddress = txtAddress.getText();
        staff s = new staff(staffId, staffName, staffphone, staffAddress, staffPassword, power);
        if(!staffName.equals("")&&!staffPassword.equals("")&&!staffId.equals("")){
            if(staffBLL.addStaff(s)>0){
            JOptionPane.showMessageDialog(null, "Thêm thành công.");
            load();
            clear();
        }
        else{
            JOptionPane.showMessageDialog(null, "Thêm thất bại.");
        }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin nhân viên cần thêm.");
        }
    }//GEN-LAST:event_btnAaddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if(!txtUsername.getText().equals("")&&!txtPassword.getText().equals("")&&!txtName.getText().equals("")){
            String id = txtUsername.getText();
            String staffName = txtName.getText();
            String staffPassword = txtPassword.getText();
            String staffAddress = txtAddress.getText();
            String staffPower = CBpower.getSelectedItem().toString();
            int power;
            if(staffPower.equals("Nhân viên")) power =1;
            else if(staffPower.equals("Admin")) power =2;
            else power = 3;
            String staffPhone = txtPhone.getText();
            if(staffBLL.getStaffById(id)!=null){
                staff s = new staff(id, staffName, staffPhone, staffAddress, staffPassword, power);
                if(staffBLL.updateStaff(s)>1){
                    JOptionPane.showMessageDialog(null, "Cập nhật thành công.");
                    load();
                    clear();
                } else{
                    JOptionPane.showMessageDialog(null, "Cập nhật thất bại.");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Không tìm thấy nhân viên cần sửa.");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Vui lòng chọn nhân viên cần sửa.");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if(!txtUsername.getText().equals("")){
            if(staffBLL.getStaffById(txtUsername.getText())!=null){
                if(staffBLL.deleteSupplier(txtUsername.getText())>0){
                    JOptionPane.showMessageDialog(null, "Xóa thành công.");
                    load();
                    clear();
                }else JOptionPane.showMessageDialog(null, "Xóa thất bại.");
            
        }else{
            JOptionPane.showMessageDialog(null, "Không tìm thấy nhân viên cần xóa.");
        }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng chọn nhân viên cấn xóa.");
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed

        String txtSearch = this.txtSearch.getText();
        
        if(!txtSearch.equals("")){
           ArrayList<staff> listId = staffBLL.searchById(txtSearch);
           ArrayList<staff> listName = staffBLL.searchByName(txtSearch);
           ArrayList<staff> listPhone = staffBLL.searchByPhone(txtSearch);
        if(!listId.isEmpty()){
            showTableSearch(listId);
            
        }
        else if(!listName.isEmpty()){
            showTableSearch(listName);
        }
        else if(!listPhone.isEmpty()){
            showTableSearch(listPhone);
        }
        else JOptionPane.showMessageDialog(null, "Không tìm thấy.");
        }
        else{
            JOptionPane.showMessageDialog(null, "Vui long nhập dữ liệu cần tìm kiếm.");
            load();
        }
    }//GEN-LAST:event_jButton38ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBpower;
    private javax.swing.JButton btnAadd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton jButton38;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable12;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
